version: '3.7'
services: 
  frontend:
    image: node:10-alpine
    volumes: 
      - ./frontend:/app
    command: sh -c 'cd /app && yarn && yarn serve'
    ports: 
      - 8080:8080
  backend:
    image: node:10-alpine
    volumes: 
      - ./backend:/app
    command: sh -c 'cd /app && yarn && yarn start:dev'
    environment: 
      MYSQL_HOST: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: database
    ports: 
      - 3000:3000
  db:
    image: mysql:5.7
    volumes: 
      - mysql:/var/lib/mysql
    environment: 
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports: 
      - 3306:3306
volumes:
  mysql: